image: microsoft/dotnet:sdk

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script:
          - export PROJECT_NAME=src/Net.Data.Commons/Net.Data.Commons.csproj
          - export TEST_NAME=test/Net.Data.Commons.Test/Net.Data.Commons.Test.csproj
          - dotnet restore
          - dotnet build $PROJECT_NAME
          - dotnet test $TEST_NAME
