name: .NET

on:
  push:
    branches: 
      - main
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'
    tags:
      - '*'

  pull_request:
    branches: 
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    # checks-out repository
    - uses: actions/checkout@v4

    # Setup a dotnet cli and tools
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.x

    # Install tools
    - name: Install tools
      run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.1.9

    # Restore
    - name: Restore
      run: dotnet restore
    
    # Build
    - name: Build
      run: dotnet build --configuration Release --no-restore 

    # Test
    - name: Test
      run: dotnet test --configuration Release --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='./TestResults/'
    
    # Package
    - name: Package
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: dotnet pack -p:PackageVersion=${{ env.PACKAGE_VERSION }} --configuration Release --no-restore -o src/DataQI.Commons/lib
      env:
        PACKAGE_VERSION: ${{ github.ref_name }}

    # Upload
    - name: Publish Artifacts
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: ${{ github.workspace }}/src/DataQI.Commons/lib/*.nupkg
        retention-days: 7

    # Coverage
    - name: Publish Coverage
      if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/hotfix/') || startsWith(github.ref, 'refs/heads/release/') }}
      uses: codecov/codecov-action@v4
      with:
        directory: ${{ github.workspace }}/test/DataQI.Commons.Test/TestResults
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  deploy-nuget:
    name: Deploy to Nuget
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: prod
    
    steps:
    # Download
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: artifacts

    # NuGet  
    - name: Publish
      run: dotnet nuget push --skip-duplicate --api-key $NUGET_AUTH_TOKEN --source https://api.nuget.org/v3/index.json  *.nupkg
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}